/*
 * CFD
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"fmt"
	"log"
	"net/http"

	_ "github.com/lib/pq"

	openapi "github.com/mrothstein74/sample-go-cfd/go"

	_ "github.com/hellofresh/health-go/v4/checks/postgres"
)

func main() {
	log.Printf("Server started")

	if err := openapi.OpenDb(); err != nil {
		panic(err)
	}

	openapi.SeedMenuItems()

	CartApiService := openapi.NewCartApiService()
	CartApiController := openapi.NewCartApiController(CartApiService)

	ImageApiService := openapi.NewImageApiService()
	ImageApiController := openapi.NewImageApiController(ImageApiService)

	MenuApiService := openapi.NewMenuApiService()
	MenuApiController := openapi.NewMenuApiController(MenuApiService)

	router := openapi.NewRouter(CartApiController, ImageApiController, MenuApiController)

	fmt.Println("listening")

	log.Fatal(http.ListenAndServe(":8080", router))

}
