/*
 * CFD
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"os"
)



// CartApiRouter defines the required methods for binding the api requests to a responses for the CartApi
// The CartApiRouter implementation should parse necessary information from the http request,
// pass the data to a CartApiServicer to perform the required actions, then write the service results to the http response.
type CartApiRouter interface { 
	AddCartItem(http.ResponseWriter, *http.Request)
	DeleteCartItem(http.ResponseWriter, *http.Request)
	ListCart(http.ResponseWriter, *http.Request)
}
// ImageApiRouter defines the required methods for binding the api requests to a responses for the ImageApi
// The ImageApiRouter implementation should parse necessary information from the http request,
// pass the data to a ImageApiServicer to perform the required actions, then write the service results to the http response.
type ImageApiRouter interface { 
	AddImage(http.ResponseWriter, *http.Request)
	DeleteImage(http.ResponseWriter, *http.Request)
	GetImage(http.ResponseWriter, *http.Request)
}
// MenuApiRouter defines the required methods for binding the api requests to a responses for the MenuApi
// The MenuApiRouter implementation should parse necessary information from the http request,
// pass the data to a MenuApiServicer to perform the required actions, then write the service results to the http response.
type MenuApiRouter interface { 
	AddMenuItem(http.ResponseWriter, *http.Request)
	ListMenu(http.ResponseWriter, *http.Request)
	ShowMenuItemById(http.ResponseWriter, *http.Request)
}


// CartApiServicer defines the api actions for the CartApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type CartApiServicer interface { 
	AddCartItem(context.Context, MenuItem) (ImplResponse, error)
	DeleteCartItem(context.Context, int32) (ImplResponse, error)
	ListCart(context.Context, int32) (ImplResponse, error)
}


// ImageApiServicer defines the api actions for the ImageApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type ImageApiServicer interface { 
	AddImage(context.Context, *os.File) (ImplResponse, error)
	DeleteImage(context.Context, int32) (ImplResponse, error)
	GetImage(context.Context, int32) (ImplResponse, error)
}


// MenuApiServicer defines the api actions for the MenuApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type MenuApiServicer interface { 
	AddMenuItem(context.Context, MenuItem) (ImplResponse, error)
	ListMenu(context.Context, int32) (ImplResponse, error)
	ShowMenuItemById(context.Context, string) (ImplResponse, error)
}
