/*
 * Continous Food Delievery
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// AddCartItem - Add a menu item a cart
func AddCartItem(c *gin.Context) {
	var menuItem MenuItem
	var cartItem CartItem

	if err := c.BindJSON(&menuItem); err != nil {
		return
	}

	err := DB.Create(&CartItem{
		MenuItem: menuItem,
	}).Error
	if err != nil {
		panic(err)
	}

	c.JSON(http.StatusOK, gin.H{"data": cartItem})
}

// DeleteCartItem - Remove item from cart
func DeleteCartItem(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ListCart - List all cart items
func ListCart(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
