/*
 * Continous Food Delievery
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// AddImage - Add an image to the restaraunt
func AddImage(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeleteImage - Remove image
func DeleteImage(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetImage - Get image
func GetImage(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
