/*
 * Continous Food Delievery
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// AddMenuItem - Create a menu item
func AddMenuItem(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ListMenu - List all menu items
func ListMenu(c *gin.Context) {
	var menuiItems []MenuItem
	DB.Find(&menuiItems)

	c.JSON(http.StatusOK, menuiItems)
}

// ShowMenuItemById - Info for a specific menu item
func ShowMenuItemById(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
