/*
 * Continous Food Delievery
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"strconv"

	"github.com/gin-gonic/gin"
)

// AddImage - Add an image to the restaraunt
func AddImage(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeleteImage - Remove image
func DeleteImage(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetImage - Get image
func GetImage(c *gin.Context) {
	id := c.Param("imageId")
	result, _ := strconv.Atoi(id)

	var menuiItems []MenuItem
	DB.Find(&menuiItems)

	for _, mi := range menuiItems {
		x := int(mi.ImageId)
		if x == result {
			DB.Find(&mi.ImageId)
			c.JSON(http.StatusOK, mi.Image)
			return
		}
	}
	c.JSON(http.StatusNotFound, gin.H{"message": "image not found"})
}
