/*
 * CFD
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
	"os"
)

// ImageApiService is a service that implements the logic for the ImageApiServicer
// This service should implement the business logic for every endpoint for the ImageApi API.
// Include any external packages or services that will be required by this service.
type ImageApiService struct {
}

// NewImageApiService creates a default api service
func NewImageApiService() ImageApiServicer {
	return &ImageApiService{}
}

// AddImage - Add an image to the restaraunt
func (s *ImageApiService) AddImage(ctx context.Context, fileName *os.File) (ImplResponse, error) {
	// TODO - update AddImage with the required logic for this service method.
	// Add api_image_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, AddImage200Response{}) or use other options such as http.Ok ...
	//return Response(200, AddImage200Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("AddImage method not implemented")
}

// DeleteImage - Remove image
func (s *ImageApiService) DeleteImage(ctx context.Context, imageId int32) (ImplResponse, error) {
	// TODO - update DeleteImage with the required logic for this service method.
	// Add api_image_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(201, {}) or use other options such as http.Ok ...
	//return Response(201, nil),nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteImage method not implemented")
}

// GetImage - Get image
func (s *ImageApiService) GetImage(ctx context.Context, imageId int32) (ImplResponse, error) {
	// TODO - update GetImage with the required logic for this service method.
	// Add api_image_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, *os.File{}) or use other options such as http.Ok ...
	//return Response(200, *os.File{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetImage method not implemented")
}
