/*
 * CFD
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"

	_ "github.com/lib/pq"
)

// MenuApiService is a service that implements the logic for the MenuApiServicer
// This service should implement the business logic for every endpoint for the MenuApi API.
// Include any external packages or services that will be required by this service.
type MenuApiService struct {
}

// NewMenuApiService creates a default api service
func NewMenuApiService() MenuApiServicer {
	return &MenuApiService{}
}

// AddMenuItem - Create a menu item
func (s *MenuApiService) AddMenuItem(ctx context.Context, menuItem MenuItem) (ImplResponse, error) {
	// TODO - update AddMenuItem with the required logic for this service method.
	// Add api_menu_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(201, {}) or use other options such as http.Ok ...
	//return Response(201, nil),nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("AddMenuItem method not implemented")
}

// ListMenu - List all menu items
func (s *MenuApiService) ListMenu(ctx context.Context, limit int32) (ImplResponse, error) {

	// TODO - update ListMenu with the required logic for this service method.
	// Add api_menu_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []MenuItem{}) or use other options such as http.Ok ...
	//return Response(200, []MenuItem{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	var mi []MenuItem
	DB.WithContext(ctx).Find(&mi)

	return Response(http.StatusNotImplemented, nil), errors.New("ListMenu method not implemented")
}

// ShowMenuItemById - Info for a specific menu item
func (s *MenuApiService) ShowMenuItemById(ctx context.Context, itemId string) (ImplResponse, error) {
	// TODO - update ShowMenuItemById with the required logic for this service method.
	// Add api_menu_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, MenuItem{}) or use other options such as http.Ok ...
	//return Response(200, MenuItem{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ShowMenuItemById method not implemented")
}
