/*
 * CFD
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// CartApiService is a service that implements the logic for the CartApiServicer
// This service should implement the business logic for every endpoint for the CartApi API.
// Include any external packages or services that will be required by this service.
type CartApiService struct {
}

// NewCartApiService creates a default api service
func NewCartApiService() CartApiServicer {
	return &CartApiService{}
}

// AddCartItem - Add a menu item a cart
func (s *CartApiService) AddCartItem(ctx context.Context, menuItem MenuItem) (ImplResponse, error) {
	// TODO - update AddCartItem with the required logic for this service method.
	// Add api_cart_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(201, {}) or use other options such as http.Ok ...
	//return Response(201, nil),nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("AddCartItem method not implemented")
}

// DeleteCartItem - Remove item from cart
func (s *CartApiService) DeleteCartItem(ctx context.Context, itemId int32) (ImplResponse, error) {
	// TODO - update DeleteCartItem with the required logic for this service method.
	// Add api_cart_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(201, {}) or use other options such as http.Ok ...
	//return Response(201, nil),nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteCartItem method not implemented")
}

// ListCart - List all cart items
func (s *CartApiService) ListCart(ctx context.Context, limit int32) (ImplResponse, error) {
	// TODO - update ListCart with the required logic for this service method.
	// Add api_cart_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []MenuItem{}) or use other options such as http.Ok ...
	//return Response(200, []MenuItem{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ListCart method not implemented")
}
