/*
 * CFD
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AddImage200Response struct {

	ImageId int32 `json:"imageId,omitempty"`
}

// AssertAddImage200ResponseRequired checks if the required fields are not zero-ed
func AssertAddImage200ResponseRequired(obj AddImage200Response) error {
	return nil
}

// AssertRecurseAddImage200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AddImage200Response (e.g. [][]AddImage200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAddImage200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAddImage200Response, ok := obj.(AddImage200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAddImage200ResponseRequired(aAddImage200Response)
	})
}
